//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.02.26 at 11:51:25 AM PKT 
//


package org.cdisc.ns.odm.v121;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlEnumValue;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for EditPointType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <pre>
 * &lt;simpleType name="EditPointType"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="Monitoring"/&gt;
 *     &lt;enumeration value="DataManagement"/&gt;
 *     &lt;enumeration value="DBAudit"/&gt;
 *     &lt;maxLength value="14"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "EditPointType")
@XmlEnum
public enum EditPointType {

    @XmlEnumValue("Monitoring")
    MONITORING("Monitoring"),
    @XmlEnumValue("DataManagement")
    DATA_MANAGEMENT("DataManagement"),
    @XmlEnumValue("DBAudit")
    DB_AUDIT("DBAudit");
    private final String value;

    EditPointType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static EditPointType fromValue(String v) {
        for (EditPointType c: EditPointType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
