//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.05.26 at 11:33:10 AM EDT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.cdisc.org/ns/odm/v1.3", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package org.cdisc.ns.odm.v130;
