//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.09.14 at 08:47:21 PM EDT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.openclinica.org/ns/odm_ext_v130/v3.1-sb", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package org.openclinica.ns.odm_ext_v130.v31_sb;
