//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.11.17 at 09:37:57 PM EST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.openclinica.org/ns/response/v3.1", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package org.openclinica.ns.response.v31;
