//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.04.21 at 06:21:07 PM EDT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.openclinica.org/ns/response/v3.1", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package org.openclinica.ns.response.v31;
