//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.02.26 at 11:51:25 AM PKT 
//

@jakarta.xml.bind.annotation.XmlSchema(namespace = "http://www.openclinica.org/ns/response/v3.1", elementFormDefault = jakarta.xml.bind.annotation.XmlNsForm.QUALIFIED)
package org.openclinica.ns.response.v31;
