//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.02.07 at 01:14:29 PM EST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.openclinica.org/ns/rules/v3.1", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package org.openclinica.ns.rules.v31;
