//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.05.31 at 07:00:09 PM PKT 
//


package org.openclinica.ns.rules.v31;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for RuleAssignmentType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="RuleAssignmentType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{http://www.openclinica.org/ns/rules/v3.1}Target"/&gt;
 *         &lt;element ref="{http://www.openclinica.org/ns/rules/v3.1}RunOnSchedule" minOccurs="0"/&gt;
 *         &lt;element ref="{http://www.openclinica.org/ns/rules/v3.1}RuleRef" maxOccurs="unbounded"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RuleAssignmentType", propOrder = {
    "target",
    "runOnSchedule",
    "ruleRef"
})
public class RuleAssignmentType
    implements Serializable
{

    @XmlElement(name = "Target", required = true)
    protected TargetType target;
    @XmlElement(name = "RunOnSchedule")
    protected RunOnScheduleType runOnSchedule;
    @XmlElement(name = "RuleRef", required = true)
    protected List<RuleRefType> ruleRef;

    /**
     * Gets the value of the target property.
     * 
     * @return
     *     possible object is
     *     {@link TargetType }
     *     
     */
    public TargetType getTarget() {
        return target;
    }

    /**
     * Sets the value of the target property.
     * 
     * @param value
     *     allowed object is
     *     {@link TargetType }
     *     
     */
    public void setTarget(TargetType value) {
        this.target = value;
    }

    public boolean isSetTarget() {
        return (this.target!= null);
    }

    /**
     * Gets the value of the runOnSchedule property.
     * 
     * @return
     *     possible object is
     *     {@link RunOnScheduleType }
     *     
     */
    public RunOnScheduleType getRunOnSchedule() {
        return runOnSchedule;
    }

    /**
     * Sets the value of the runOnSchedule property.
     * 
     * @param value
     *     allowed object is
     *     {@link RunOnScheduleType }
     *     
     */
    public void setRunOnSchedule(RunOnScheduleType value) {
        this.runOnSchedule = value;
    }

    public boolean isSetRunOnSchedule() {
        return (this.runOnSchedule!= null);
    }

    /**
     * Gets the value of the ruleRef property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the ruleRef property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRuleRef().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link RuleRefType }
     * 
     * 
     */
    public List<RuleRefType> getRuleRef() {
        if (ruleRef == null) {
            ruleRef = new ArrayList<RuleRefType>();
        }
        return this.ruleRef;
    }

    public boolean isSetRuleRef() {
        return ((this.ruleRef!= null)&&(!this.ruleRef.isEmpty()));
    }

    public void unsetRuleRef() {
        this.ruleRef = null;
    }

}
