//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.10.10 at 03:40:48 PM PKT 
//


package org.openclinica.ns.odm_ext_v130.v31;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.openclinica.ns.odm_ext_v130.v31 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _MultiSelectListRef_QNAME = new QName("http://www.openclinica.org/ns/odm_ext_v130/v3.1", "MultiSelectListRef");
    private final static QName _MultiSelectList_QNAME = new QName("http://www.openclinica.org/ns/odm_ext_v130/v3.1", "MultiSelectList");
    private final static QName _MultiSelectListItem_QNAME = new QName("http://www.openclinica.org/ns/odm_ext_v130/v3.1", "MultiSelectListItem");
    private final static QName _StudyGroupClassList_QNAME = new QName("http://www.openclinica.org/ns/odm_ext_v130/v3.1", "StudyGroupClassList");
    private final static QName _ConfigurationParameters_QNAME = new QName("http://www.openclinica.org/ns/odm_ext_v130/v3.1", "ConfigurationParameters");
    private final static QName _FormLayoutRef_QNAME = new QName("http://www.openclinica.org/ns/odm_ext_v130/v3.1", "FormLayoutRef");
    private final static QName _PermissionTags_QNAME = new QName("http://www.openclinica.org/ns/odm_ext_v130/v3.1", "PermissionTags");
    private final static QName _FormLayoutDef_QNAME = new QName("http://www.openclinica.org/ns/odm_ext_v130/v3.1", "FormLayoutDef");
    private final static QName _StudyGroupItem_QNAME = new QName("http://www.openclinica.org/ns/odm_ext_v130/v3.1", "StudyGroupItem");
    private final static QName _StudyDetails_QNAME = new QName("http://www.openclinica.org/ns/odm_ext_v130/v3.1", "StudyDetails");
    private final static QName _StudyDescriptionAndStatus_QNAME = new QName("http://www.openclinica.org/ns/odm_ext_v130/v3.1", "StudyDescriptionAndStatus");
    private final static QName _ConditionsAndEligibility_QNAME = new QName("http://www.openclinica.org/ns/odm_ext_v130/v3.1", "ConditionsAndEligibility");
    private final static QName _Age_QNAME = new QName("http://www.openclinica.org/ns/odm_ext_v130/v3.1", "Age");
    private final static QName _FacilityInformation_QNAME = new QName("http://www.openclinica.org/ns/odm_ext_v130/v3.1", "FacilityInformation");
    private final static QName _RelatedInformation_QNAME = new QName("http://www.openclinica.org/ns/odm_ext_v130/v3.1", "RelatedInformation");
    private final static QName _StudyParameterConfiguration_QNAME = new QName("http://www.openclinica.org/ns/odm_ext_v130/v3.1", "StudyParameterConfiguration");
    private final static QName _StudyParameterListRef_QNAME = new QName("http://www.openclinica.org/ns/odm_ext_v130/v3.1", "StudyParameterListRef");
    private final static QName _StudyParameterList_QNAME = new QName("http://www.openclinica.org/ns/odm_ext_v130/v3.1", "StudyParameterList");
    private final static QName _StudyParameterListItem_QNAME = new QName("http://www.openclinica.org/ns/odm_ext_v130/v3.1", "StudyParameterListItem");
    private final static QName _EventDefinitionDetails_QNAME = new QName("http://www.openclinica.org/ns/odm_ext_v130/v3.1", "EventDefinitionDetails");
    private final static QName _FormDetails_QNAME = new QName("http://www.openclinica.org/ns/odm_ext_v130/v3.1", "FormDetails");
    private final static QName _PresentInEventDefinition_QNAME = new QName("http://www.openclinica.org/ns/odm_ext_v130/v3.1", "PresentInEventDefinition");
    private final static QName _ItemGroupDetails_QNAME = new QName("http://www.openclinica.org/ns/odm_ext_v130/v3.1", "ItemGroupDetails");
    private final static QName _PresentInForm_QNAME = new QName("http://www.openclinica.org/ns/odm_ext_v130/v3.1", "PresentInForm");
    private final static QName _ItemGroupRepeat_QNAME = new QName("http://www.openclinica.org/ns/odm_ext_v130/v3.1", "ItemGroupRepeat");
    private final static QName _ItemDetails_QNAME = new QName("http://www.openclinica.org/ns/odm_ext_v130/v3.1", "ItemDetails");
    private final static QName _ItemPresentInForm_QNAME = new QName("http://www.openclinica.org/ns/odm_ext_v130/v3.1", "ItemPresentInForm");
    private final static QName _ItemResponse_QNAME = new QName("http://www.openclinica.org/ns/odm_ext_v130/v3.1", "ItemResponse");
    private final static QName _SimpleConditionalDisplay_QNAME = new QName("http://www.openclinica.org/ns/odm_ext_v130/v3.1", "SimpleConditionalDisplay");
    private final static QName _SubjectGroupData_QNAME = new QName("http://www.openclinica.org/ns/odm_ext_v130/v3.1", "SubjectGroupData");
    private final static QName _AuditLogs_QNAME = new QName("http://www.openclinica.org/ns/odm_ext_v130/v3.1", "AuditLogs");
    private final static QName _AuditLog_QNAME = new QName("http://www.openclinica.org/ns/odm_ext_v130/v3.1", "AuditLog");
    private final static QName _Links_QNAME = new QName("http://www.openclinica.org/ns/odm_ext_v130/v3.1", "Links");
    private final static QName _Link_QNAME = new QName("http://www.openclinica.org/ns/odm_ext_v130/v3.1", "Link");
    private final static QName _DiscrepancyNotes_QNAME = new QName("http://www.openclinica.org/ns/odm_ext_v130/v3.1", "DiscrepancyNotes");
    private final static QName _DiscrepancyNote_QNAME = new QName("http://www.openclinica.org/ns/odm_ext_v130/v3.1", "DiscrepancyNote");
    private final static QName _ChildNote_QNAME = new QName("http://www.openclinica.org/ns/odm_ext_v130/v3.1", "ChildNote");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.openclinica.ns.odm_ext_v130.v31
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link OCodmComplexTypeDefinitionMultiSelectListRef }
     * 
     */
    public OCodmComplexTypeDefinitionMultiSelectListRef createOCodmComplexTypeDefinitionMultiSelectListRef() {
        return new OCodmComplexTypeDefinitionMultiSelectListRef();
    }

    /**
     * Create an instance of {@link OCodmComplexTypeDefinitionMultiSelectList }
     * 
     */
    public OCodmComplexTypeDefinitionMultiSelectList createOCodmComplexTypeDefinitionMultiSelectList() {
        return new OCodmComplexTypeDefinitionMultiSelectList();
    }

    /**
     * Create an instance of {@link OCodmComplexTypeDefinitionMultiSelectListItem }
     * 
     */
    public OCodmComplexTypeDefinitionMultiSelectListItem createOCodmComplexTypeDefinitionMultiSelectListItem() {
        return new OCodmComplexTypeDefinitionMultiSelectListItem();
    }

    /**
     * Create an instance of {@link OCodmComplexTypeDefinitionStudyGroupClassList }
     * 
     */
    public OCodmComplexTypeDefinitionStudyGroupClassList createOCodmComplexTypeDefinitionStudyGroupClassList() {
        return new OCodmComplexTypeDefinitionStudyGroupClassList();
    }

    /**
     * Create an instance of {@link OCodmComplexTypeDefinitionConfigurationParameters }
     * 
     */
    public OCodmComplexTypeDefinitionConfigurationParameters createOCodmComplexTypeDefinitionConfigurationParameters() {
        return new OCodmComplexTypeDefinitionConfigurationParameters();
    }

    /**
     * Create an instance of {@link OCodmComplexTypeDefinitionFormLayoutRef }
     * 
     */
    public OCodmComplexTypeDefinitionFormLayoutRef createOCodmComplexTypeDefinitionFormLayoutRef() {
        return new OCodmComplexTypeDefinitionFormLayoutRef();
    }

    /**
     * Create an instance of {@link OCodmComplexTypeDefinitionPermissionTags }
     * 
     */
    public OCodmComplexTypeDefinitionPermissionTags createOCodmComplexTypeDefinitionPermissionTags() {
        return new OCodmComplexTypeDefinitionPermissionTags();
    }

    /**
     * Create an instance of {@link OCodmComplexTypeDefinitionFormLayoutDef }
     * 
     */
    public OCodmComplexTypeDefinitionFormLayoutDef createOCodmComplexTypeDefinitionFormLayoutDef() {
        return new OCodmComplexTypeDefinitionFormLayoutDef();
    }

    /**
     * Create an instance of {@link OCodmComplexTypeDefinitionStudyGroupItem }
     * 
     */
    public OCodmComplexTypeDefinitionStudyGroupItem createOCodmComplexTypeDefinitionStudyGroupItem() {
        return new OCodmComplexTypeDefinitionStudyGroupItem();
    }

    /**
     * Create an instance of {@link OCodmComplexTypeDefinitionStudyDetails }
     * 
     */
    public OCodmComplexTypeDefinitionStudyDetails createOCodmComplexTypeDefinitionStudyDetails() {
        return new OCodmComplexTypeDefinitionStudyDetails();
    }

    /**
     * Create an instance of {@link OCodmComplexTypeDefinitionStudyDescriptionAndStatus }
     * 
     */
    public OCodmComplexTypeDefinitionStudyDescriptionAndStatus createOCodmComplexTypeDefinitionStudyDescriptionAndStatus() {
        return new OCodmComplexTypeDefinitionStudyDescriptionAndStatus();
    }

    /**
     * Create an instance of {@link OCodmComplexTypeDefinitionConditionsAndEligibility }
     * 
     */
    public OCodmComplexTypeDefinitionConditionsAndEligibility createOCodmComplexTypeDefinitionConditionsAndEligibility() {
        return new OCodmComplexTypeDefinitionConditionsAndEligibility();
    }

    /**
     * Create an instance of {@link OCodmComplexTypeDefinitionAge }
     * 
     */
    public OCodmComplexTypeDefinitionAge createOCodmComplexTypeDefinitionAge() {
        return new OCodmComplexTypeDefinitionAge();
    }

    /**
     * Create an instance of {@link OCodmComplexTypeDefinitionFacilityInformation }
     * 
     */
    public OCodmComplexTypeDefinitionFacilityInformation createOCodmComplexTypeDefinitionFacilityInformation() {
        return new OCodmComplexTypeDefinitionFacilityInformation();
    }

    /**
     * Create an instance of {@link OCodmComplexTypeDefinitionRelatedInformation }
     * 
     */
    public OCodmComplexTypeDefinitionRelatedInformation createOCodmComplexTypeDefinitionRelatedInformation() {
        return new OCodmComplexTypeDefinitionRelatedInformation();
    }

    /**
     * Create an instance of {@link OCodmComplexTypeDefinitionStudyParameterConfiguration }
     * 
     */
    public OCodmComplexTypeDefinitionStudyParameterConfiguration createOCodmComplexTypeDefinitionStudyParameterConfiguration() {
        return new OCodmComplexTypeDefinitionStudyParameterConfiguration();
    }

    /**
     * Create an instance of {@link OCodmComplexTypeDefinitionStudyParameterListRef }
     * 
     */
    public OCodmComplexTypeDefinitionStudyParameterListRef createOCodmComplexTypeDefinitionStudyParameterListRef() {
        return new OCodmComplexTypeDefinitionStudyParameterListRef();
    }

    /**
     * Create an instance of {@link OCodmComplexTypeDefinitionStudyParameterList }
     * 
     */
    public OCodmComplexTypeDefinitionStudyParameterList createOCodmComplexTypeDefinitionStudyParameterList() {
        return new OCodmComplexTypeDefinitionStudyParameterList();
    }

    /**
     * Create an instance of {@link OCodmComplexTypeDefinitionStudyParameterListItem }
     * 
     */
    public OCodmComplexTypeDefinitionStudyParameterListItem createOCodmComplexTypeDefinitionStudyParameterListItem() {
        return new OCodmComplexTypeDefinitionStudyParameterListItem();
    }

    /**
     * Create an instance of {@link OCodmComplexTypeDefinitionEventDefinitionDetails }
     * 
     */
    public OCodmComplexTypeDefinitionEventDefinitionDetails createOCodmComplexTypeDefinitionEventDefinitionDetails() {
        return new OCodmComplexTypeDefinitionEventDefinitionDetails();
    }

    /**
     * Create an instance of {@link OCodmComplexTypeDefinitionFormDetails }
     * 
     */
    public OCodmComplexTypeDefinitionFormDetails createOCodmComplexTypeDefinitionFormDetails() {
        return new OCodmComplexTypeDefinitionFormDetails();
    }

    /**
     * Create an instance of {@link OCodmComplexTypeDefinitionPresentInEventDefinition }
     * 
     */
    public OCodmComplexTypeDefinitionPresentInEventDefinition createOCodmComplexTypeDefinitionPresentInEventDefinition() {
        return new OCodmComplexTypeDefinitionPresentInEventDefinition();
    }

    /**
     * Create an instance of {@link OCodmComplexTypeDefinitionItemGroupDetails }
     * 
     */
    public OCodmComplexTypeDefinitionItemGroupDetails createOCodmComplexTypeDefinitionItemGroupDetails() {
        return new OCodmComplexTypeDefinitionItemGroupDetails();
    }

    /**
     * Create an instance of {@link OCodmComplexTypeDefinitionPresentInForm }
     * 
     */
    public OCodmComplexTypeDefinitionPresentInForm createOCodmComplexTypeDefinitionPresentInForm() {
        return new OCodmComplexTypeDefinitionPresentInForm();
    }

    /**
     * Create an instance of {@link OCodmComplexTypeDefinitionItemGroupRepeat }
     * 
     */
    public OCodmComplexTypeDefinitionItemGroupRepeat createOCodmComplexTypeDefinitionItemGroupRepeat() {
        return new OCodmComplexTypeDefinitionItemGroupRepeat();
    }

    /**
     * Create an instance of {@link OCodmComplexTypeDefinitionItemDetails }
     * 
     */
    public OCodmComplexTypeDefinitionItemDetails createOCodmComplexTypeDefinitionItemDetails() {
        return new OCodmComplexTypeDefinitionItemDetails();
    }

    /**
     * Create an instance of {@link OCodmComplexTypeDefinitionItemPresentInForm }
     * 
     */
    public OCodmComplexTypeDefinitionItemPresentInForm createOCodmComplexTypeDefinitionItemPresentInForm() {
        return new OCodmComplexTypeDefinitionItemPresentInForm();
    }

    /**
     * Create an instance of {@link OCodmComplexTypeDefinitionItemResponse }
     * 
     */
    public OCodmComplexTypeDefinitionItemResponse createOCodmComplexTypeDefinitionItemResponse() {
        return new OCodmComplexTypeDefinitionItemResponse();
    }

    /**
     * Create an instance of {@link OCodmComplexTypeDefinitionSimpleConditionalDisplay }
     * 
     */
    public OCodmComplexTypeDefinitionSimpleConditionalDisplay createOCodmComplexTypeDefinitionSimpleConditionalDisplay() {
        return new OCodmComplexTypeDefinitionSimpleConditionalDisplay();
    }

    /**
     * Create an instance of {@link OCodmComplexTypeDefinitionSubjectGroupData }
     * 
     */
    public OCodmComplexTypeDefinitionSubjectGroupData createOCodmComplexTypeDefinitionSubjectGroupData() {
        return new OCodmComplexTypeDefinitionSubjectGroupData();
    }

    /**
     * Create an instance of {@link OCodmComplexTypeDefinitionAuditLogs }
     * 
     */
    public OCodmComplexTypeDefinitionAuditLogs createOCodmComplexTypeDefinitionAuditLogs() {
        return new OCodmComplexTypeDefinitionAuditLogs();
    }

    /**
     * Create an instance of {@link OCodmComplexTypeDefinitionAuditLog }
     * 
     */
    public OCodmComplexTypeDefinitionAuditLog createOCodmComplexTypeDefinitionAuditLog() {
        return new OCodmComplexTypeDefinitionAuditLog();
    }

    /**
     * Create an instance of {@link OCodmComplexTypeDefinitionLinks }
     * 
     */
    public OCodmComplexTypeDefinitionLinks createOCodmComplexTypeDefinitionLinks() {
        return new OCodmComplexTypeDefinitionLinks();
    }

    /**
     * Create an instance of {@link OCodmComplexTypeDefinitionLink }
     * 
     */
    public OCodmComplexTypeDefinitionLink createOCodmComplexTypeDefinitionLink() {
        return new OCodmComplexTypeDefinitionLink();
    }

    /**
     * Create an instance of {@link OCodmComplexTypeDefinitionDiscrepancyNotes }
     * 
     */
    public OCodmComplexTypeDefinitionDiscrepancyNotes createOCodmComplexTypeDefinitionDiscrepancyNotes() {
        return new OCodmComplexTypeDefinitionDiscrepancyNotes();
    }

    /**
     * Create an instance of {@link OCodmComplexTypeDefinitionDiscrepancyNote }
     * 
     */
    public OCodmComplexTypeDefinitionDiscrepancyNote createOCodmComplexTypeDefinitionDiscrepancyNote() {
        return new OCodmComplexTypeDefinitionDiscrepancyNote();
    }

    /**
     * Create an instance of {@link OCodmComplexTypeDefinitionChildNote }
     * 
     */
    public OCodmComplexTypeDefinitionChildNote createOCodmComplexTypeDefinitionChildNote() {
        return new OCodmComplexTypeDefinitionChildNote();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link OCodmComplexTypeDefinitionMultiSelectListRef }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link OCodmComplexTypeDefinitionMultiSelectListRef }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.openclinica.org/ns/odm_ext_v130/v3.1", name = "MultiSelectListRef")
    public JAXBElement<OCodmComplexTypeDefinitionMultiSelectListRef> createMultiSelectListRef(OCodmComplexTypeDefinitionMultiSelectListRef value) {
        return new JAXBElement<OCodmComplexTypeDefinitionMultiSelectListRef>(_MultiSelectListRef_QNAME, OCodmComplexTypeDefinitionMultiSelectListRef.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link OCodmComplexTypeDefinitionMultiSelectList }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link OCodmComplexTypeDefinitionMultiSelectList }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.openclinica.org/ns/odm_ext_v130/v3.1", name = "MultiSelectList")
    public JAXBElement<OCodmComplexTypeDefinitionMultiSelectList> createMultiSelectList(OCodmComplexTypeDefinitionMultiSelectList value) {
        return new JAXBElement<OCodmComplexTypeDefinitionMultiSelectList>(_MultiSelectList_QNAME, OCodmComplexTypeDefinitionMultiSelectList.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link OCodmComplexTypeDefinitionMultiSelectListItem }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link OCodmComplexTypeDefinitionMultiSelectListItem }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.openclinica.org/ns/odm_ext_v130/v3.1", name = "MultiSelectListItem")
    public JAXBElement<OCodmComplexTypeDefinitionMultiSelectListItem> createMultiSelectListItem(OCodmComplexTypeDefinitionMultiSelectListItem value) {
        return new JAXBElement<OCodmComplexTypeDefinitionMultiSelectListItem>(_MultiSelectListItem_QNAME, OCodmComplexTypeDefinitionMultiSelectListItem.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link OCodmComplexTypeDefinitionStudyGroupClassList }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link OCodmComplexTypeDefinitionStudyGroupClassList }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.openclinica.org/ns/odm_ext_v130/v3.1", name = "StudyGroupClassList")
    public JAXBElement<OCodmComplexTypeDefinitionStudyGroupClassList> createStudyGroupClassList(OCodmComplexTypeDefinitionStudyGroupClassList value) {
        return new JAXBElement<OCodmComplexTypeDefinitionStudyGroupClassList>(_StudyGroupClassList_QNAME, OCodmComplexTypeDefinitionStudyGroupClassList.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link OCodmComplexTypeDefinitionConfigurationParameters }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link OCodmComplexTypeDefinitionConfigurationParameters }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.openclinica.org/ns/odm_ext_v130/v3.1", name = "ConfigurationParameters")
    public JAXBElement<OCodmComplexTypeDefinitionConfigurationParameters> createConfigurationParameters(OCodmComplexTypeDefinitionConfigurationParameters value) {
        return new JAXBElement<OCodmComplexTypeDefinitionConfigurationParameters>(_ConfigurationParameters_QNAME, OCodmComplexTypeDefinitionConfigurationParameters.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link OCodmComplexTypeDefinitionFormLayoutRef }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link OCodmComplexTypeDefinitionFormLayoutRef }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.openclinica.org/ns/odm_ext_v130/v3.1", name = "FormLayoutRef")
    public JAXBElement<OCodmComplexTypeDefinitionFormLayoutRef> createFormLayoutRef(OCodmComplexTypeDefinitionFormLayoutRef value) {
        return new JAXBElement<OCodmComplexTypeDefinitionFormLayoutRef>(_FormLayoutRef_QNAME, OCodmComplexTypeDefinitionFormLayoutRef.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link OCodmComplexTypeDefinitionPermissionTags }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link OCodmComplexTypeDefinitionPermissionTags }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.openclinica.org/ns/odm_ext_v130/v3.1", name = "PermissionTags")
    public JAXBElement<OCodmComplexTypeDefinitionPermissionTags> createPermissionTags(OCodmComplexTypeDefinitionPermissionTags value) {
        return new JAXBElement<OCodmComplexTypeDefinitionPermissionTags>(_PermissionTags_QNAME, OCodmComplexTypeDefinitionPermissionTags.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link OCodmComplexTypeDefinitionFormLayoutDef }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link OCodmComplexTypeDefinitionFormLayoutDef }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.openclinica.org/ns/odm_ext_v130/v3.1", name = "FormLayoutDef")
    public JAXBElement<OCodmComplexTypeDefinitionFormLayoutDef> createFormLayoutDef(OCodmComplexTypeDefinitionFormLayoutDef value) {
        return new JAXBElement<OCodmComplexTypeDefinitionFormLayoutDef>(_FormLayoutDef_QNAME, OCodmComplexTypeDefinitionFormLayoutDef.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link OCodmComplexTypeDefinitionStudyGroupItem }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link OCodmComplexTypeDefinitionStudyGroupItem }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.openclinica.org/ns/odm_ext_v130/v3.1", name = "StudyGroupItem")
    public JAXBElement<OCodmComplexTypeDefinitionStudyGroupItem> createStudyGroupItem(OCodmComplexTypeDefinitionStudyGroupItem value) {
        return new JAXBElement<OCodmComplexTypeDefinitionStudyGroupItem>(_StudyGroupItem_QNAME, OCodmComplexTypeDefinitionStudyGroupItem.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link OCodmComplexTypeDefinitionStudyDetails }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link OCodmComplexTypeDefinitionStudyDetails }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.openclinica.org/ns/odm_ext_v130/v3.1", name = "StudyDetails")
    public JAXBElement<OCodmComplexTypeDefinitionStudyDetails> createStudyDetails(OCodmComplexTypeDefinitionStudyDetails value) {
        return new JAXBElement<OCodmComplexTypeDefinitionStudyDetails>(_StudyDetails_QNAME, OCodmComplexTypeDefinitionStudyDetails.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link OCodmComplexTypeDefinitionStudyDescriptionAndStatus }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link OCodmComplexTypeDefinitionStudyDescriptionAndStatus }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.openclinica.org/ns/odm_ext_v130/v3.1", name = "StudyDescriptionAndStatus")
    public JAXBElement<OCodmComplexTypeDefinitionStudyDescriptionAndStatus> createStudyDescriptionAndStatus(OCodmComplexTypeDefinitionStudyDescriptionAndStatus value) {
        return new JAXBElement<OCodmComplexTypeDefinitionStudyDescriptionAndStatus>(_StudyDescriptionAndStatus_QNAME, OCodmComplexTypeDefinitionStudyDescriptionAndStatus.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link OCodmComplexTypeDefinitionConditionsAndEligibility }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link OCodmComplexTypeDefinitionConditionsAndEligibility }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.openclinica.org/ns/odm_ext_v130/v3.1", name = "ConditionsAndEligibility")
    public JAXBElement<OCodmComplexTypeDefinitionConditionsAndEligibility> createConditionsAndEligibility(OCodmComplexTypeDefinitionConditionsAndEligibility value) {
        return new JAXBElement<OCodmComplexTypeDefinitionConditionsAndEligibility>(_ConditionsAndEligibility_QNAME, OCodmComplexTypeDefinitionConditionsAndEligibility.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link OCodmComplexTypeDefinitionAge }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link OCodmComplexTypeDefinitionAge }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.openclinica.org/ns/odm_ext_v130/v3.1", name = "Age")
    public JAXBElement<OCodmComplexTypeDefinitionAge> createAge(OCodmComplexTypeDefinitionAge value) {
        return new JAXBElement<OCodmComplexTypeDefinitionAge>(_Age_QNAME, OCodmComplexTypeDefinitionAge.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link OCodmComplexTypeDefinitionFacilityInformation }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link OCodmComplexTypeDefinitionFacilityInformation }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.openclinica.org/ns/odm_ext_v130/v3.1", name = "FacilityInformation")
    public JAXBElement<OCodmComplexTypeDefinitionFacilityInformation> createFacilityInformation(OCodmComplexTypeDefinitionFacilityInformation value) {
        return new JAXBElement<OCodmComplexTypeDefinitionFacilityInformation>(_FacilityInformation_QNAME, OCodmComplexTypeDefinitionFacilityInformation.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link OCodmComplexTypeDefinitionRelatedInformation }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link OCodmComplexTypeDefinitionRelatedInformation }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.openclinica.org/ns/odm_ext_v130/v3.1", name = "RelatedInformation")
    public JAXBElement<OCodmComplexTypeDefinitionRelatedInformation> createRelatedInformation(OCodmComplexTypeDefinitionRelatedInformation value) {
        return new JAXBElement<OCodmComplexTypeDefinitionRelatedInformation>(_RelatedInformation_QNAME, OCodmComplexTypeDefinitionRelatedInformation.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link OCodmComplexTypeDefinitionStudyParameterConfiguration }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link OCodmComplexTypeDefinitionStudyParameterConfiguration }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.openclinica.org/ns/odm_ext_v130/v3.1", name = "StudyParameterConfiguration")
    public JAXBElement<OCodmComplexTypeDefinitionStudyParameterConfiguration> createStudyParameterConfiguration(OCodmComplexTypeDefinitionStudyParameterConfiguration value) {
        return new JAXBElement<OCodmComplexTypeDefinitionStudyParameterConfiguration>(_StudyParameterConfiguration_QNAME, OCodmComplexTypeDefinitionStudyParameterConfiguration.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link OCodmComplexTypeDefinitionStudyParameterListRef }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link OCodmComplexTypeDefinitionStudyParameterListRef }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.openclinica.org/ns/odm_ext_v130/v3.1", name = "StudyParameterListRef")
    public JAXBElement<OCodmComplexTypeDefinitionStudyParameterListRef> createStudyParameterListRef(OCodmComplexTypeDefinitionStudyParameterListRef value) {
        return new JAXBElement<OCodmComplexTypeDefinitionStudyParameterListRef>(_StudyParameterListRef_QNAME, OCodmComplexTypeDefinitionStudyParameterListRef.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link OCodmComplexTypeDefinitionStudyParameterList }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link OCodmComplexTypeDefinitionStudyParameterList }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.openclinica.org/ns/odm_ext_v130/v3.1", name = "StudyParameterList")
    public JAXBElement<OCodmComplexTypeDefinitionStudyParameterList> createStudyParameterList(OCodmComplexTypeDefinitionStudyParameterList value) {
        return new JAXBElement<OCodmComplexTypeDefinitionStudyParameterList>(_StudyParameterList_QNAME, OCodmComplexTypeDefinitionStudyParameterList.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link OCodmComplexTypeDefinitionStudyParameterListItem }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link OCodmComplexTypeDefinitionStudyParameterListItem }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.openclinica.org/ns/odm_ext_v130/v3.1", name = "StudyParameterListItem")
    public JAXBElement<OCodmComplexTypeDefinitionStudyParameterListItem> createStudyParameterListItem(OCodmComplexTypeDefinitionStudyParameterListItem value) {
        return new JAXBElement<OCodmComplexTypeDefinitionStudyParameterListItem>(_StudyParameterListItem_QNAME, OCodmComplexTypeDefinitionStudyParameterListItem.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link OCodmComplexTypeDefinitionEventDefinitionDetails }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link OCodmComplexTypeDefinitionEventDefinitionDetails }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.openclinica.org/ns/odm_ext_v130/v3.1", name = "EventDefinitionDetails")
    public JAXBElement<OCodmComplexTypeDefinitionEventDefinitionDetails> createEventDefinitionDetails(OCodmComplexTypeDefinitionEventDefinitionDetails value) {
        return new JAXBElement<OCodmComplexTypeDefinitionEventDefinitionDetails>(_EventDefinitionDetails_QNAME, OCodmComplexTypeDefinitionEventDefinitionDetails.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link OCodmComplexTypeDefinitionFormDetails }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link OCodmComplexTypeDefinitionFormDetails }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.openclinica.org/ns/odm_ext_v130/v3.1", name = "FormDetails")
    public JAXBElement<OCodmComplexTypeDefinitionFormDetails> createFormDetails(OCodmComplexTypeDefinitionFormDetails value) {
        return new JAXBElement<OCodmComplexTypeDefinitionFormDetails>(_FormDetails_QNAME, OCodmComplexTypeDefinitionFormDetails.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link OCodmComplexTypeDefinitionPresentInEventDefinition }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link OCodmComplexTypeDefinitionPresentInEventDefinition }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.openclinica.org/ns/odm_ext_v130/v3.1", name = "PresentInEventDefinition")
    public JAXBElement<OCodmComplexTypeDefinitionPresentInEventDefinition> createPresentInEventDefinition(OCodmComplexTypeDefinitionPresentInEventDefinition value) {
        return new JAXBElement<OCodmComplexTypeDefinitionPresentInEventDefinition>(_PresentInEventDefinition_QNAME, OCodmComplexTypeDefinitionPresentInEventDefinition.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link OCodmComplexTypeDefinitionItemGroupDetails }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link OCodmComplexTypeDefinitionItemGroupDetails }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.openclinica.org/ns/odm_ext_v130/v3.1", name = "ItemGroupDetails")
    public JAXBElement<OCodmComplexTypeDefinitionItemGroupDetails> createItemGroupDetails(OCodmComplexTypeDefinitionItemGroupDetails value) {
        return new JAXBElement<OCodmComplexTypeDefinitionItemGroupDetails>(_ItemGroupDetails_QNAME, OCodmComplexTypeDefinitionItemGroupDetails.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link OCodmComplexTypeDefinitionPresentInForm }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link OCodmComplexTypeDefinitionPresentInForm }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.openclinica.org/ns/odm_ext_v130/v3.1", name = "PresentInForm")
    public JAXBElement<OCodmComplexTypeDefinitionPresentInForm> createPresentInForm(OCodmComplexTypeDefinitionPresentInForm value) {
        return new JAXBElement<OCodmComplexTypeDefinitionPresentInForm>(_PresentInForm_QNAME, OCodmComplexTypeDefinitionPresentInForm.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link OCodmComplexTypeDefinitionItemGroupRepeat }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link OCodmComplexTypeDefinitionItemGroupRepeat }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.openclinica.org/ns/odm_ext_v130/v3.1", name = "ItemGroupRepeat")
    public JAXBElement<OCodmComplexTypeDefinitionItemGroupRepeat> createItemGroupRepeat(OCodmComplexTypeDefinitionItemGroupRepeat value) {
        return new JAXBElement<OCodmComplexTypeDefinitionItemGroupRepeat>(_ItemGroupRepeat_QNAME, OCodmComplexTypeDefinitionItemGroupRepeat.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link OCodmComplexTypeDefinitionItemDetails }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link OCodmComplexTypeDefinitionItemDetails }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.openclinica.org/ns/odm_ext_v130/v3.1", name = "ItemDetails")
    public JAXBElement<OCodmComplexTypeDefinitionItemDetails> createItemDetails(OCodmComplexTypeDefinitionItemDetails value) {
        return new JAXBElement<OCodmComplexTypeDefinitionItemDetails>(_ItemDetails_QNAME, OCodmComplexTypeDefinitionItemDetails.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link OCodmComplexTypeDefinitionItemPresentInForm }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link OCodmComplexTypeDefinitionItemPresentInForm }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.openclinica.org/ns/odm_ext_v130/v3.1", name = "ItemPresentInForm")
    public JAXBElement<OCodmComplexTypeDefinitionItemPresentInForm> createItemPresentInForm(OCodmComplexTypeDefinitionItemPresentInForm value) {
        return new JAXBElement<OCodmComplexTypeDefinitionItemPresentInForm>(_ItemPresentInForm_QNAME, OCodmComplexTypeDefinitionItemPresentInForm.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link OCodmComplexTypeDefinitionItemResponse }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link OCodmComplexTypeDefinitionItemResponse }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.openclinica.org/ns/odm_ext_v130/v3.1", name = "ItemResponse")
    public JAXBElement<OCodmComplexTypeDefinitionItemResponse> createItemResponse(OCodmComplexTypeDefinitionItemResponse value) {
        return new JAXBElement<OCodmComplexTypeDefinitionItemResponse>(_ItemResponse_QNAME, OCodmComplexTypeDefinitionItemResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link OCodmComplexTypeDefinitionSimpleConditionalDisplay }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link OCodmComplexTypeDefinitionSimpleConditionalDisplay }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.openclinica.org/ns/odm_ext_v130/v3.1", name = "SimpleConditionalDisplay")
    public JAXBElement<OCodmComplexTypeDefinitionSimpleConditionalDisplay> createSimpleConditionalDisplay(OCodmComplexTypeDefinitionSimpleConditionalDisplay value) {
        return new JAXBElement<OCodmComplexTypeDefinitionSimpleConditionalDisplay>(_SimpleConditionalDisplay_QNAME, OCodmComplexTypeDefinitionSimpleConditionalDisplay.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link OCodmComplexTypeDefinitionSubjectGroupData }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link OCodmComplexTypeDefinitionSubjectGroupData }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.openclinica.org/ns/odm_ext_v130/v3.1", name = "SubjectGroupData")
    public JAXBElement<OCodmComplexTypeDefinitionSubjectGroupData> createSubjectGroupData(OCodmComplexTypeDefinitionSubjectGroupData value) {
        return new JAXBElement<OCodmComplexTypeDefinitionSubjectGroupData>(_SubjectGroupData_QNAME, OCodmComplexTypeDefinitionSubjectGroupData.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link OCodmComplexTypeDefinitionAuditLogs }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link OCodmComplexTypeDefinitionAuditLogs }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.openclinica.org/ns/odm_ext_v130/v3.1", name = "AuditLogs")
    public JAXBElement<OCodmComplexTypeDefinitionAuditLogs> createAuditLogs(OCodmComplexTypeDefinitionAuditLogs value) {
        return new JAXBElement<OCodmComplexTypeDefinitionAuditLogs>(_AuditLogs_QNAME, OCodmComplexTypeDefinitionAuditLogs.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link OCodmComplexTypeDefinitionAuditLog }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link OCodmComplexTypeDefinitionAuditLog }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.openclinica.org/ns/odm_ext_v130/v3.1", name = "AuditLog")
    public JAXBElement<OCodmComplexTypeDefinitionAuditLog> createAuditLog(OCodmComplexTypeDefinitionAuditLog value) {
        return new JAXBElement<OCodmComplexTypeDefinitionAuditLog>(_AuditLog_QNAME, OCodmComplexTypeDefinitionAuditLog.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link OCodmComplexTypeDefinitionLinks }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link OCodmComplexTypeDefinitionLinks }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.openclinica.org/ns/odm_ext_v130/v3.1", name = "Links")
    public JAXBElement<OCodmComplexTypeDefinitionLinks> createLinks(OCodmComplexTypeDefinitionLinks value) {
        return new JAXBElement<OCodmComplexTypeDefinitionLinks>(_Links_QNAME, OCodmComplexTypeDefinitionLinks.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link OCodmComplexTypeDefinitionLink }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link OCodmComplexTypeDefinitionLink }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.openclinica.org/ns/odm_ext_v130/v3.1", name = "Link")
    public JAXBElement<OCodmComplexTypeDefinitionLink> createLink(OCodmComplexTypeDefinitionLink value) {
        return new JAXBElement<OCodmComplexTypeDefinitionLink>(_Link_QNAME, OCodmComplexTypeDefinitionLink.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link OCodmComplexTypeDefinitionDiscrepancyNotes }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link OCodmComplexTypeDefinitionDiscrepancyNotes }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.openclinica.org/ns/odm_ext_v130/v3.1", name = "DiscrepancyNotes")
    public JAXBElement<OCodmComplexTypeDefinitionDiscrepancyNotes> createDiscrepancyNotes(OCodmComplexTypeDefinitionDiscrepancyNotes value) {
        return new JAXBElement<OCodmComplexTypeDefinitionDiscrepancyNotes>(_DiscrepancyNotes_QNAME, OCodmComplexTypeDefinitionDiscrepancyNotes.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link OCodmComplexTypeDefinitionDiscrepancyNote }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link OCodmComplexTypeDefinitionDiscrepancyNote }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.openclinica.org/ns/odm_ext_v130/v3.1", name = "DiscrepancyNote")
    public JAXBElement<OCodmComplexTypeDefinitionDiscrepancyNote> createDiscrepancyNote(OCodmComplexTypeDefinitionDiscrepancyNote value) {
        return new JAXBElement<OCodmComplexTypeDefinitionDiscrepancyNote>(_DiscrepancyNote_QNAME, OCodmComplexTypeDefinitionDiscrepancyNote.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link OCodmComplexTypeDefinitionChildNote }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link OCodmComplexTypeDefinitionChildNote }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.openclinica.org/ns/odm_ext_v130/v3.1", name = "ChildNote")
    public JAXBElement<OCodmComplexTypeDefinitionChildNote> createChildNote(OCodmComplexTypeDefinitionChildNote value) {
        return new JAXBElement<OCodmComplexTypeDefinitionChildNote>(_ChildNote_QNAME, OCodmComplexTypeDefinitionChildNote.class, null, value);
    }

}
